#!/usr/bin/env bash

# Validate Pull Request Title
echo "Validating PR Title..."

# Example PR Title
TITLE="feat(ECOMA-18): Add Healthy Experiment"
echo "PR Title: $TITLE"

# Validation Regex
if [[ ! "$TITLE" =~ ^(fix|release|feat|hotfix|build|test)\([A-Za-z0-9/-]+\):\ [A-Za-z0-9-]+\ [A-Za-z ]+$ ]]; then
    echo "Invalid PR title format. Please follow the required format:"
    echo "type(scope): {TicketNum}-task name"
    exit 1
fi

echo "PR title is valid."
